### PR TITLE
Makes hiredis a development dependency

### LINKED ISSUE #15: remove hiredis dependency
Hi, hiredis doesn't support TLS, is it possible to remove the dependency from modis?

### PR DESCRIPTION
**Pull request by fdoxyz**
Closes #15

`hiredis` gave us a hard time the other day because we were accidentally using it instead of the driver we expected to be running our Redis connection (we had TLS only connections enabled). Giving projects that use `modis` the option to choose their Redis driver would be really appreciated.

From what I was able to find in the codebase `hiredis` is only being directly used for benchmarks. Making it a development dependency should allow to keep that functionality without imposing it on downstream projects. I think this warrants for a major bump when released to rubygems because some users of the gem might be expecting `hiredis` to be transitively included in their projects and that could potentially break their apps.

### CODE REVIEW

**Comment by jgaskins** [comment]
@fdoxyz We may also need to remove the `hiredis` driver selection from [the default config](https://github.com/rpush/modis/blob/ea4946685bc883f3695e31c8ac19518aba7901ec/lib/modis.rb#L26-L28). I don't know if it'd work if we left it in, but it's probably good hygeine to remove it anyway. 🙂

**Comment by aried3r** [comment]
Hey! Thanks for this PR!

I see the failures for JRuby and I'm not sure what to do with them. Personally, I'd be okay with removing support for JRuby in the next major version, however it's easy for me to say as I don't use it.

Is there a way we can get JRuby to pass? Otherwise I'd take this chance to remove support for Rails 4.2, 5.0, 5.1 and add support for Rails 6.1 and Ruby 3.

**Comment by fdoxyz** [comment]
You're welcome @aried3r! I'll take a stab at your suggestions and will let you know

I can see the `jruby-9.2.8.0` job passing with Rails 4.2 but failing on all others, maybe relying on the more recent `9.2.x` versions could fix it. I can't be certain since I don't use JRuby either though.

**Comment by fdoxyz** [comment]
> ...maybe relying on the more recent 9.2.x versions could fix it.

It worked ^

Turns out [Rails 5.2 doesn't support Ruby 3](https://github.com/rails/rails/issues/40938#issuecomment-751569171) (builds were failing), so I added an exclusion rule for that one. 

Also, given that this would be part of a major release bump I went ahead and removed Ruby versions that are EOL from the test matrix. I can revert that if it sounds better to keep them.

**Comment by aried3r** [comment]
Thank you, looks great!

> Also, given that this would be part of a major release bump I went ahead and removed Ruby versions that are EOL from the test matrix. I can revert that if it sounds better to keep them.

This gem hasn't seen a release in quite a while. While I'd definitely go that route in the future, can we re-add 2.3 and above? It's still quite heavily used [apparently](https://stats.rubygems.org/).

I know the exception matrix will get bigger since newer Rails versions don't support old Rubies, but I think Rails 5.2 and Ruby 2.3 are a good lower bound for the next release. And that way at least a few more people can benefit from your PR. WDYT?

Could I also ask you to change the gemspec file to reflect the supported Rails versions?

**Comment by fdoxyz** [comment]
> can we re-add 2.3 and above?

✅

TIL about https://stats.rubygems.org/  😄

> Could I also ask you to change the gemspec file to reflect the supported Rails versions?

✅

**Comment by aried3r** [comment]
Thank you! It seems there's lots of interest for this PR given the reactions. I'll see to it that it gets released soon.

**Comment by aried3r** [comment]
A new release has just been pushed to rubygems. https://rubygems.org/gems/modis/versions/4.0.0

**Pull request merged**
