### PR TITLE
Support redis gem v5.x

### PR DESCRIPTION
**Pull request by benlangfeld**

### CODE REVIEW

**Comment by sharang-d** [comment]
Hi @benlangfeld, thanks for maintaining the rpush gems.

Can you please let me know if you have an estimate in mind for when this would be implemented? Or if there are any blockers?
Additionally, do let me know if I can help! I'd love to have the library support Redis 5+ because this library is the most recently updated library in the push-notification sending space and I'd love to keep it that way :)

**Comment by benlangfeld** [comment]
> Hi @benlangfeld, thanks for maintaining the rpush gems.
> 
> Can you please let me know if you have an estimate in mind for when this would be implemented? Or if there are any blockers? Additionally, do let me know if I can help! I'd love to have the library support Redis 5+ because this library is the most recently updated library in the push-notification sending space and I'd love to keep it that way :)

This is blocked on the failing tests here, and I don't have time to work on it. If someone can submit a version of this with passing tests, I can review it.

**Comment by sharang-d** [comment]
I attempted something @ https://github.com/rpush/modis/pull/47.

**Comment by rustemmukhamadiev** [comment]
@benlangfeld would be great to complete this PR and start support redis gem v5

**Comment by benlangfeld** [comment]
Just need a changelog entry here which I'll add when I get to my desk.

**Pull request merged**
